#!/bin/bash

JOB_NAME=spring-app
BASE_DIR=/var/vcap
SYS_DIR=$BASE_DIR/sys
RUN_DIR=$SYS_DIR/run/$JOB_NAME
LOG_DIR=$SYS_DIR/log/$JOB_NAME
PIDFILE=$RUN_DIR/$JOB_NAME.pid
RUNAS=vcap

# Path to the JAR file
APP_JAR=$BASE_DIR/packages/$JOB_NAME/app.jar

# Set environment variables for the port and message from BOSH properties
PORT=<%= p("port") %>
GREETING="<%= p("greeting") %>"

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    #Set the JAVA_HOME
    export JAVA_HOME=/var/vcap/packages/java
    #Add the JAVA_HOME to the PATH
    export PATH=$JAVA_HOME/bin:$PATH

    exec java -jar $APP_JAR \
      --server.port=$PORT \
      --GREETING="$GREETING" \
      1>>$LOG_DIR/stdout.log \
      2>>$LOG_DIR/stderr.log
    ;;

  stop)
    kill -9 `cat $PIDFILE`
    rm -f $PIDFILE
    ;;

  *)
    echo "Usage: ctl {start|stop}" ;;

esac